# Generated by Django 3.2.16 on 2024-10-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20241003_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
